### ISSUE TITLE
Doesn't work with Server 2019

### ISSUE THREAD

**Issue by thomas-illiet** [rgl/packer-provisioner-windows-update#23] opened 2018-10-08 09:22 UTC
Hello Rui Lopes :)

Your module doesn't work with Server 2019 :/

Config :
```json
{
    "variables": {
      "os_name": "Win_Srv_STD_CORE_2019_English",
      "iso_url": ".\\iso\\en_windows_server_2019_x64_dvd_3c2cf1202.iso",
      "iso_checksum_type": "sha256",
      "iso_checksum": "7B463563206DCE275F2D3FF77AC36C430052FAE161CD4F8B31F3DC7AF1C3F418",
      "switch_name": "Lab",
      "vlan_id": ""
    },
    "builders": [
      {
        "type": "hyperv-iso",
        "vm_name": "{{ user `os_name` }}",
        "iso_url": "{{ user `iso_url` }}",
        "iso_checksum_type": "{{user `iso_checksum_type`}}",
        "iso_checksum": "{{user `iso_checksum`}}",
        "temp_path": "./Tmp",
        "disk_size": "40000",
        "communicator": "winrm",
        "winrm_username": "Administrator",
        "winrm_password": "password",
        "winrm_timeout": "8h",
        "shutdown_command": "C:/windows/system32/sysprep/sysprep.exe /generalize /oobe /unattend:C:/Windows/system32/unattended.xml /quiet /shutdown /mode:vm",
        "shutdown_timeout": "30m",
        "ram_size": 2048,
        "enable_dynamic_memory": "true",
        "cpu": 4,
        "generation": 2,
        "switch_name": "{{user `switch_name`}}",
        "vlan_id": "{{user `vlan_id`}}",
        "boot_wait": "0s",
        "boot_command": [
          "aaaaa<wait>a<wait>a<wait>"
        ],
        "output_directory": "./Tmp/Output/{{ user `os_name` }}/",
        "guest_additions_mode":"disable",
        "enable_secure_boot":true,
        "secondary_iso_images": [
          "./Tmp/BootDisk/win2019stdcore.iso"
        ]
      }
    ],
    "provisioners": [
        {
            "type": "windows-update",
            "filters": [
                "exclude:$_.Title -like '*Preview*'",
                "include:$_.Title -like '*Cumulative Update for Windows*'",
                "include:$_.AutoSelectOnWebSites"
            ]
        }
    ],
    "post-processors": [
      {
        "type": "vagrant",
        "compression_level": 9,
        "keep_input_artifact": false,
        "output": "./Output/{{ user `os_name` }}_{{.Provider}}.box",
        "vagrantfile_template": "./Templates/win2019stdcore/vagrantfile.template"
      }
    ]
  }
```

Result Logs :
```powershell
==> hyperv-iso: Creating build directory...
==> hyperv-iso: Retrieving ISO
    hyperv-iso: Using file in-place: file:///G:/v2/PackerTemplates/PackerTemplates/Iso/en_windows_server_2019_x64_dvd_3c2cf1202.iso
==> hyperv-iso: Creating switch 'Lab' if required...
==> hyperv-iso:     switch 'Lab' already exists. Will not delete on cleanup...
==> hyperv-iso: Creating virtual machine...
==> hyperv-iso: Enabling Integration Service...
==> hyperv-iso: Setting boot drive to os dvd drive G:/v2/PackerTemplates/PackerTemplates/Iso/en_windows_server_2019_x64_dvd_3c2cf1202.iso ...
==> hyperv-iso: Mounting os dvd drive G:/v2/PackerTemplates/PackerTemplates/Iso/en_windows_server_2019_x64_dvd_3c2cf1202.iso ...
==> hyperv-iso: Skipping mounting Integration Services Setup Disk...
==> hyperv-iso: Mounting secondary DVD images...
==> hyperv-iso: Mounting secondary dvd drive ./Tmp/BootDisk/win2019stdcore.iso ...
==> hyperv-iso: Configuring vlan...
==> hyperv-iso: Starting the virtual machine...
==> hyperv-iso: Attempting to connect with vmconnect...
==> hyperv-iso: Host IP for the HyperV machine: 172.16.10.69
==> hyperv-iso: Typing the boot command...
==> hyperv-iso: Waiting for WinRM to become available...
    hyperv-iso: WinRM connected.
    hyperv-iso: #< CLIXML
    hyperv-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> hyperv-iso: Connected to WinRM!
==> hyperv-iso: Uploading the Windows update elevated script...
==> hyperv-iso: Uploading the Windows update script...
==> hyperv-iso: Running Windows update...
    hyperv-iso: #< CLIXML
    hyperv-iso: Searching for Windows updates...
    hyperv-iso: ERROR: Exception from HRESULT: 0x8024402C
    hyperv-iso: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 141
    hyperv-iso: ERROR: at <ScriptBlock>, <No file>: line 1
    hyperv-iso: ERROR EXCEPTION: System.Runtime.InteropServices.COMException (0x8024402C): Exception from HRESULT: 0x8024402C
    hyperv-iso: ERROR EXCEPTION:    at System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
    hyperv-iso: ERROR EXCEPTION:    at CallSite.Target(Closure , CallSite , ComObject , String )
    hyperv-iso: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
    hyperv-iso: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
    hyperv-iso: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
    hyperv-iso: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    hyperv-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> hyperv-iso: Disconnecting from vmconnect...
==> hyperv-iso: Clean up secondary dvd drives...
==> hyperv-iso: Clean up os dvd drive...
==> hyperv-iso: Unregistering and deleting virtual machine...
==> hyperv-iso: Deleting output directory...
==> hyperv-iso: Deleting build directory...
Build 'hyperv-iso' errored: Windows update script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> hyperv-iso: Windows update script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
````

Thx
Thomas

**Comment by rgl** [comment] 2018-10-08 09:49
try it with packer 1.2.5 (later versions have a problem with restart)

**Comment by thomas-illiet** [comment] 2018-10-08 11:15
same error :/

```powershell
==> hyperv-iso: Creating temporary directory...
==> hyperv-iso: Downloading or copying ISO
    hyperv-iso: Downloading or copying: file:///G:/v2/PackerTemplates/PackerTemplates/Iso/en_windows_server_2019_x64_dvd_3c2cf1202.iso
==> hyperv-iso: Creating switch 'Lab' if required...
==> hyperv-iso:     switch 'Lab' already exists. Will not delete on cleanup...
==> hyperv-iso: Creating virtual machine...
==> hyperv-iso: Enabling Integration Service...
==> hyperv-iso: Setting boot drive to os dvd drive G:/v2/PackerTemplates/PackerTemplates/Iso/en_windows_server_2019_x64_dvd_3c2cf1202.iso ...
==> hyperv-iso: Mounting os dvd drive G:/v2/PackerTemplates/PackerTemplates/Iso/en_windows_server_2019_x64_dvd_3c2cf1202.iso ...
==> hyperv-iso: Skipping mounting Integration Services Setup Disk...
==> hyperv-iso: Mounting secondary DVD images...
==> hyperv-iso: Mounting secondary dvd drive ./Tmp/BootDisk/win2019stdcore.iso ...
==> hyperv-iso: Configuring vlan...
==> hyperv-iso: Starting the virtual machine...
==> hyperv-iso: Attempting to connect with vmconnect...
==> hyperv-iso: Host IP for the HyperV machine: 172.16.10.69
==> hyperv-iso: Typing the boot command...
==> hyperv-iso: Waiting for WinRM to become available...
    hyperv-iso: WinRM connected.
    hyperv-iso: #< CLIXML
    hyperv-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> hyperv-iso: Connected to WinRM!
==> hyperv-iso: Uploading the Windows update elevated script...
==> hyperv-iso: Uploading the Windows update script...
==> hyperv-iso: Running Windows update...
    hyperv-iso: #< CLIXML
    hyperv-iso: Searching for Windows updates...
    hyperv-iso: ERROR: Exception from HRESULT: 0x8024402C
    hyperv-iso: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 141
    hyperv-iso: ERROR: at <ScriptBlock>, <No file>: line 1
    hyperv-iso: ERROR EXCEPTION: System.Runtime.InteropServices.COMException (0x8024402C): Exception from HRESULT: 0x8024402C
    hyperv-iso: ERROR EXCEPTION:    at System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
    hyperv-iso: ERROR EXCEPTION:    at CallSite.Target(Closure , CallSite , ComObject , String )
    hyperv-iso: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
    hyperv-iso: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
    hyperv-iso: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
    hyperv-iso: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    hyperv-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> hyperv-iso: Disconnecting from vmconnect...
==> hyperv-iso: Clean up secondary dvd drives...
==> hyperv-iso: Clean up os dvd drive...
==> hyperv-iso: Unregistering and deleting virtual machine...
==> hyperv-iso: Deleting output directory...
==> hyperv-iso: Deleting temporary directory...
Build 'hyperv-iso' errored: Windows update script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> hyperv-iso: Windows update script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
```

Thx

**Comment by rgl** [comment] 2018-10-14 18:50
Please try with the new 0.6.0 and packer 1.2.5 (restart is broken after that release, so stick with 1.2.5 for now), winrm, and use the provision step without any options, i.e.:

```json
{
    "provisioners": [
        {
            "type": "windows-update"
        }
    ]
}
```

It should now install all recommended updates alike the windows update ui.

Also, doing a quick look for 0x8024402C found https://support.microsoft.com/en-us/help/900936/error-code-0x8024402c-when-you-try-to-install-updates-on-windows-updat maybe that sheds some clues about the problem.

**Comment by thomas-illiet** [comment] 2018-10-16 12:02
Perfect Job !

**Comment by thomas-illiet** [comment] 2018-10-16 12:20
Humm or not :) windows doesn't install update :/

```
==> hyperv-iso: Creating temporary directory...
==> hyperv-iso: Downloading or copying ISO
    hyperv-iso: Downloading or copying: file:///F:/v2/PackerTemplates/PackerTemplates/Iso/en_windows_server_2019_x64_dvd_3c2cf1202.iso
==> hyperv-iso: Creating switch 'Lab' if required...
==> hyperv-iso:     switch 'Lab' already exists. Will not delete on cleanup...
==> hyperv-iso: Creating virtual machine...
==> hyperv-iso: Enabling Integration Service...
==> hyperv-iso: Setting boot drive to os dvd drive F:/v2/PackerTemplates/PackerTemplates/Iso/en_windows_server_2019_x64_dvd_3c2cf1202.iso ...
==> hyperv-iso: Mounting os dvd drive F:/v2/PackerTemplates/PackerTemplates/Iso/en_windows_server_2019_x64_dvd_3c2cf1202.iso ...
==> hyperv-iso: Skipping mounting Integration Services Setup Disk...
==> hyperv-iso: Mounting secondary DVD images...
==> hyperv-iso: Mounting secondary dvd drive ./Tmp/BootDisk/win2019std.iso ...
==> hyperv-iso: Configuring vlan...
==> hyperv-iso: Starting the virtual machine...
==> hyperv-iso: Attempting to connect with vmconnect...
==> hyperv-iso: Host IP for the HyperV machine: 172.16.10.42
==> hyperv-iso: Typing the boot command...
==> hyperv-iso: Waiting for WinRM to become available...
    hyperv-iso: WinRM connected.
    hyperv-iso: #< CLIXML
    hyperv-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> hyperv-iso: Connected to WinRM!
==> hyperv-iso: Uploading the Windows update elevated script...
==> hyperv-iso: Uploading the Windows update check for reboot required elevated script...
==> hyperv-iso: Uploading the Windows update script...
==> hyperv-iso: Running Windows update...
    hyperv-iso: Searching for Windows updates...
    hyperv-iso: Found Windows update (2018-10-09; 7784.43 MB): 2018-10 Cumulative Update for Windows Server 2016 (1809) for x64-based Systems (KB4464330)
    hyperv-iso: Found Windows update (2018-10-09; 45.85 MB): Windows Malicious Software Removal Tool x64 - October 2018 (KB890830)
    hyperv-iso: Skipped (filter) Windows update (2018-10-15; 20.72 MB): Update for Adobe Flash Player for Windows Server 2019 (1809) for x64-based Systems (KB4462930)
    hyperv-iso: Found Windows update (2018-10-16; 166.59 MB): Definition Update for Windows Defender Antivirus - KB2267602 (Definition 1.277.1156.0)
    hyperv-iso: Downloading Windows updates (3 updates; 7996.87 MB)...
    hyperv-iso: Installing Windows updates...
==> hyperv-iso: Provisioning with Powershell...
==> hyperv-iso: Provisioning with powershell script: ./Scripts/Remove-LLMNR.ps1
==> hyperv-iso: Provisioning with Powershell...
==> hyperv-iso: Provisioning with powershell script: ./Scripts/Remove-NBT.ps1
==> hyperv-iso: Provisioning with Powershell...
```

I know I have a good connection, but minutes to download 8GO is too fast!

After ```==> hyperv-iso: Provisioning with powershell script: ./Scripts/Remove-LLMNR.ps1``` i kill packer process to update manualy windows, you can find below a screenshot :
![image](https://user-images.githubusercontent.com/2133666/47015790-37e1cf80-d14e-11e8-8b6f-f451518f7302.png)


And same error on windows server 2019 CORE & GUI :/

Do you want ISO to try (MSDN) ?

**Comment by rgl** [comment] 2018-10-16 20:32
bummer, its not really working. I'm waiting for 2019 iso to be available again, because they we removed due to https://support.microsoft.com/en-us/help/4464619/windows-10-update-history, so until then I will refrain from installing 2019.

**Comment by gstorme** [comment] 2018-11-29 15:03
I also gave it a go.

```
Searching for Windows updates...
Found Windows update (2018-11-13; 7891,49 MB): 2018-11 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB4467708)
Found Windows update (2018-10-15; 20,72 MB): Update for Adobe Flash Player for Windows Server 2019 (1809) for x64-based Systems (KB4462930)
Found Windows update (2018-11-13; 46,5 MB): Windows Malicious Software Removal Tool x64 - November 2018 (KB890830)
Found Windows update (2018-11-20; 20,72 MB): 2018-11 Security Update for Adobe Flash Player for Windows Server 2019 for x64-based Systems (KB4477029)
Found Windows update (2018-11-29; 164,89 MB): Definition Update for Windows Defender Antivirus - KB2267602 (Definition 1.281.1059.0)
Downloading Windows updates (5 updates; 8144,33 MB)...
Installing Windows updates...```
```  

About update KB4467708, the update size is not being displayed correctly by Microsoft.Update.

```
Title                           : 2018-11 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB4467708)
AutoSelectOnWebSites            : False
BundledUpdates                  : System.__ComObject
CanRequireSource                : False
Categories                      : System.__ComObject
Deadline                        :
DeltaCompressedContentAvailable : False
DeltaCompressedContentPreferred : True
Description                     : Install this update to resolve issues in Windows. For a complete listing of the issues that are included in this update, see the associated Microsoft Knowledge Base article for more information. After you install this item, you may have
                                   to restart your computer.
EulaAccepted                    : True
EulaText                        :
HandlerID                       : http://schemas.microsoft.com/msus/2016/01/UpdateHandlers/OSInstaller
Identity                        : System.__ComObject
Image                           :
InstallationBehavior            : System.__ComObject
IsBeta                          : False
IsDownloaded                    : True
IsHidden                        : False
IsInstalled                     : False
IsMandatory                     : False
IsUninstallable                 : False
Languages                       : System.__ComObject
LastDeploymentChangeTime        : 13/11/2018 0:00:00
MaxDownloadSize                 : 8274825697
MinDownloadSize                 : 0
MoreInfoUrls                    : System.__ComObject
MsrcSeverity                    :
RecommendedCpuSpeed             : 0
RecommendedHardDiskSpace        : 0
RecommendedMemory               : 0
ReleaseNotes                    :
SecurityBulletinIDs             : System.__ComObject
SupersededUpdateIDs             : System.__ComObject
SupportUrl                      : http://support.microsoft.com/help/446770
```

It displays MaxDownloadSize 8274825697, but according to https://www.catalog.update.microsoft.com/Search.aspx?q=KB4467708, this update is only 95.8 MB, which would explain the fast download.

According to the WindowsUpdateLog and the System event log, all of these updates were installed successfully, but update KB4467708 was not installed.
An extract from WindowsUpdateLog:

```
2018/11/29 15:35:04.7996321 2792  6300  DownloadManager Updates to download = 1
2018/11/29 15:35:04.7996350 2792  6300  Agent             Title = 2018-11 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB4467708)
2018/11/29 15:35:04.7996387 2792  6300  Agent             UpdateId = 89E30488-48A2-4E27-8B4C-E766CEAA4189.1
2018/11/29 15:35:25.8450169 1056  1268  Handler         Install complete for update ID: 89E30488-48A2-4E27-8B4C-E766CEAA4189.1 Return code is 0x00000000. Requires Reboot:No
```

Manual installation of it through windows update gui works, and does require a reboot.

**Comment by rgl** [comment] 2019-03-02 18:45
with the latest windows iso and updates its working fine for me. since I'm not able to reproduce this, I'll close this issue.

**Closed by rgl** 2019-03-02 18:45 UTC

**Comment by agowa338** [comment] 2019-03-11 02:18
The bug occurs, as `!$update.IsDownloaded` lies to us for some updates, it returns true, even though the update is fully downloaded, therefore this plugin does not attempt to redownload it. That's maybe why you're unable to reproduce. @rgl can you please poste which iso you used? I'm having this problem with the one from the volume licencing portal and there is no newer version.

There are two solutions to this bug:

1. Right after this packer provisioner rebooted the vm log into it and invoke an update search through the GUI, after you clicked the button, the packer plugin is able to successfully complete.
2. Apply the patch #33 to remove the check if the update got already downloaded and always redownload all necessary updates.

**Comment by rgl** [comment] 2019-03-11 06:43
I'm using the evaluation version that is on the packer template of this repository.

**Comment by Rahaman148** [comment] 2019-10-14 17:50
I am trying to create `Windows-Server-Core-2016-1809` image but getting below errors any suggestions -
![windows-server-core-2016](https://user-images.githubusercontent.com/46972124/66771750-b320b300-ee80-11e9-9c5b-85827f781f8a.JPG)
![windows-server-core-2016-2](https://user-images.githubusercontent.com/46972124/66771752-b320b300-ee80-11e9-87ec-4d7dd30e6578.JPG)

I've found other solutions here `https://support.microsoft.com/en-us/help/900936/error-code-0x8024402c-when-you-try-to-install-updates-on-windows-updat` but doesn't help.
